name: Build Next.js web application and deploy
on:
  push:
    branches:
      - develop
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: jongwooo/next-cache@v1
      - name: Install NPM dependencies
        run: npm install
      - name: Bundle .env file
        run: touch .env; echo "NEXT_PUBLIC_SERVICE_ID = ${{secrets.NEXT_PUBLIC_SERVICE_ID}}" >> .env; echo "NEXT_PUBLIC_TEMPLATE_ID = ${{secrets.NEXT_PUBLIC_TEMPLATE_ID}}" >> .env; echo "NEXT_PUBLIC_PUBLIC_KEY = ${{secrets.NEXT_PUBLIC_PUBLIC_KEY}}" >> .env
      - name: Build project assets
        run: npm run build
      - name: Copy .htaccess to out directory
        run: cp src/util/.htaccess out/.htaccess
      - name: Cache out directory
        uses: actions/cache@v4
        with:
          path: out/
          key: ${{ runner.os }}-${{ github.run_id }}-outDir-develop
  web-deploy:
    name: Deploy
    needs: build-project
    runs-on: ubuntu-latest
    steps:
      - name: Cache out directory
        uses: actions/cache@v4
        with:
          path: out/
          key: ${{ runner.os }}-${{ github.run_id }}-outDir
      - name: Push files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: out/
          server-dir: beta/
